Update the wxWidgets build procedure and documentation

diff --git a/Misc/osx-build-wx b/Misc/osx-build-wx
--- a/Misc/osx-build-wx
+++ b/Misc/osx-build-wx
@@ -1,16 +1,24 @@
 #!/bin/sh
 #
-# This script is used to build wxWidgets on Mac OS X in a way that pwsafe 
-# will run on as many MacOS versions as possible when built on that machine.
-# That also means the wxWidgets build generated by this script would depend
-# on the compilers and SDKs supported on the version of OS X it is running on.
+# This script is used to build wxWidgets on Mac OS X in a way that pwsafe will
+# run on as many MacOS versions as possible when built on that machine.  That
+# also means the wxWidgets build generated by this script would depend on the
+# compilers and SDKs supported on the version of OS X it is running on.
 # 
-# If was initially written for building wx2.8 on Snow Leopard such that the 
+# If was initially written for building wx2.8 on Snow Leopard such that the
 # pwsafe binary would run on OS X 10.4+.  It followed the documentation here:
-#   http://wiki.wxwidgets.org/Development:_wxMac
+# http://wiki.wxwidgets.org/Development:_wxMac
 #
-# See the sections "Building on Snow Leopard for Snow Leopard" and
-# "Building on Snow Leopard for Snow Leopard"
+# See the sections "Building on Snow Leopard for Snow Leopard" and "Building on
+# Snow Leopard for Snow Leopard"
+#
+# As of April 2023, this script (and the release build) have been updated to
+# mainly support macOS 10.14 and above, Xcode 14.x, and wxWidgets 3.2.1 and
+# above.  As a result, references and procedures for older platforms have
+# fallen out of maintenance.  If an older version is needed, it might be best
+# to pull it from an older GitHub release tag.
+#
+# For more information on using this script, see: README.MAC.DEVELOPERS.md
 #
 
 # Build release configuration by default
@@ -31,6 +39,19 @@ SDKPATH=
 # This is where gcc, g++ and ld required to build with 10.4 SDK should be
 TOOLCHAIN_DIR=
 
+# "make install" base directory.  For safety, we set it to pwd and don't recommend installing
+# You might want to use /usr/local if you intend to install the resulting wxWidgwts build.
+WX_PREFIX=`pwd`
+
+# Architectures to build, default comes from the workflow file but can be overriden
+# with the -a option.
+WX_ARCH=
+
+# Workflow file for the GitHub release build.  We will fetch some parameters from it.
+WORKFLOW=`dirname $0`/../.github/workflows/macos-latest.yml
+
+
+
 usage() {
     cat <<__END_USAGE__
 
@@ -38,6 +59,9 @@ usage() {
               You then run make to actually build it
 
 Usage (all flags are optional):
+	-a (arm64|x86_64)
+	    Build for a single, specified architecture.  The default is to build a Universal Binary.
+
 	-d
 	    Create Debug configuration.  Absence of this flag creates the Release configuration
 
@@ -54,7 +78,7 @@ Usage (all flags are optional):
 	    You can get the path to any installed SDK that Xcode is aware of like this
 	    xcodebuild -version -sdk macosx10.9 Path
 
-	-t <toolchain dir>
+	-T <toolchain dir>
 	    Directory where gcc-4.0, g++4.0, etc. should be.  Only required for building wx2.8 on OS X 10.9
 __END_USAGE__
 }
@@ -64,10 +88,18 @@ error() {
 	exit 1
 }
 
-while getopts "dc:t:nk:t:" opt; do
+
+
+while getopts "a:dc:t:nk:T:" opt; do
 	case $opt in
+		a)
+			case "$OPTARG" in
+				arm64|x86_64) WX_ARCH=$OPTARG;;
+				*) error Unexpected architecture: $OPTARG. Its either \"arm64\" or \"x86_64\" \(default is both\) 1>&2
+				;;
+			esac
+			;;
 		d)
-#KAI add enable-debug_info
 			DEBUG_FLAG="--enable-debug --enable-debug_info"
 			;;
 		c)
@@ -83,65 +115,131 @@ while getopts "dc:t:nk:t:" opt; do
 				carbon) TOOLKIT=CARBON;;
 				cocoa)  TOOLKIT=COCOA;;
 				*)      error Unexpected toolkit: $OPTARG. Its either \"carbon\" or \"cocoa\" \(default\) 1>&2
-						;;
+				;;
 			esac
 			;;	
-        k)
-            if [ -d $OPTARG ]
-            then
-                SDKPATH=$OPTARG
-            else
-				error Invalid directory passed for SDK path: $OPTARG
-            fi
-            ;;
-        t)
-            if [ -d $OPTARG ]
-            then
-                TOOLCHAIN_DIR=$OPTARG
-            else
-				error Invalid directory passed for toolchain dir: $OPTARG
-            fi
-            ;;
+		k)
+			if [ -d $OPTARG ]
+			then
+				SDKPATH=$OPTARG
+			else
+				error "Invalid directory passed for SDK path: $OPTARG"
+			fi
+			;;
+		T)
+			if [ -d $OPTARG ]
+			then
+				TOOLCHAIN_DIR=$OPTARG
+			else
+				error "Invalid directory passed for toolchain dir: $OPTARG"
+			fi
+			;;
 		n)
 			DRY_RUN="echo "
 			;;
 		?)
-            usage $0
+			usage $0
 			exit 1
 			;;
 	esac
 done
 
+# Get the version of wxWidgets source we are building
 WX_VER=`$CONF_SCRIPT -V | grep 'wxWidgets configure' | cut -d' ' -f3`
 
-# This might be required for 10.7 & 10.8 as well
-OSX_VER=`sw_vers -productVersion`
-if [ "$OSX_VER" = "10.9" -o "$OSX_VER" \> "10.9" ]
-then
-    if [ -z "$TOOLCHAIN_DIR" ]
+#
+# This is to build the wxOSX/Cocoa version of wxWidgets, which is what is supported on macOS 10.10 and up.
+# This code tries to build wxWidgets the same way the Github workflow builds the distribution. 
+#
+doCocoaBuild() {
+    if [ ! -f $WORKFLOW ]
     then
-        # This is where gcc-4.x etc. will be found
-        TOOLCHAIN_DIR=/Developer/usr/bin
+        error "Cannot locate the workflow file: $WORKFLOW"
     fi
-fi
+	# This is actually where 'make install' will put things.
+	WX_BUILD_DIR=$WX_PREFIX
 
-# Homebrew include path
-if [ -d "/opt/homebrew/include" ]
-then
-	# This is the HomeBrew default include path on arm64
-	homebrew_path="-I/opt/homebrew/include"
-else
-	if [ -d  "/usr/local/include" ]
+	# Fetch some parameters from the macos-latest.yaml workflow
+	if [ -z $WX_ARCH ]
 	then
-		# The default is where HomeBrew include files are installed on x86_64
-		homebrew_path="-I/usr/local/include"
-	else
-		echo "Could not find path to HomeBrew include files"
-		exit 1
+	    eval `grep WX_ARCH= $WORKFLOW | sed -E -e 's/^.*"(.*)".*$/\1/'`
 	fi
-fi
+	eval `grep MACOS_VER_MIN= $WORKFLOW | sed -E -e 's/^.*"(.*)".*$/\1/'`
 
+	# The configure command in the workflow file uses the above variables.
+	# This trick will expand them into the CONF_OPTS variable
+	CONF_OPTS=`grep ./configure $WORKFLOW | cut -w -f 3-`
+	CONF_OPTS=`eval echo $CONF_OPTS`
+
+	# This is about the only cocoa build customization we support because everything
+	# else is taken care of via "deployment target" in pwsafe-xcode6.xcodeproj
+	SDKFLAG=
+	if [ -n "$SDKPATH" ]
+	then
+		SDKFLAG="--with-macosx-sdk=$SDKPATH"
+	fi
+
+    echo "=============================="
+    echo "osx-build-wx options:"
+    echo "WX_VER" = $WX_VER
+    echo "WX_ARCH" = $WX_ARCH
+    echo "MACOS_VER_MIN" = $MACOS_VER_MIN
+    echo "WX_BUILD_DIR" = $WX_BUILD_DIR
+    echo "SDKFLAG" = $SDKFLAG
+    echo "DEBUG_FLAG" = $DEBUG_FLAG
+    echo "CONF_OPTS" = $CONF_OPTS
+    echo "=============================="
+
+	$DRY_RUN $CONF_SCRIPT $CONF_OPTS $SDKFLAG
+
+
+# These are some old configure options used with 3.0.x, just for reference...
+#                              $SDKFLAG                          \
+#                              --with-osx_cocoa                  \
+#                              --disable-shared                  \
+#                              --enable-unicode                  \
+#                              --enable-aui                      \
+#                              --with-macosx-version-min=10.10   \
+#                              $COMPATFLAG                       \
+#                              --without-liblzma                 \
+#                              --enable-cxx11                    \
+#	                          --enable-universal-binary=`uname -m`   \
+#                              $ZLIBFLAG
+
+}
+
+#
+# This is old code that built wxOSX/Carbon for old versions of Pwsafe and macOS.
+# This is no longer supported or tested an is almost certainly useless but 
+# it's kept here as a reference just in case someone needs it.
+#
 doCarbonBuild() {
+	# This might be required for 10.7 & 10.8 as well
+	OSX_VER=`sw_vers -productVersion`
+	if [ "$OSX_VER" = "10.9" -o "$OSX_VER" \> "10.9" ]
+	then
+		if [ -z "$TOOLCHAIN_DIR" ]
+		then
+			# This is where gcc-4.x etc. will be found
+			TOOLCHAIN_DIR=/Developer/usr/bin
+		fi
+	fi
+
+	# Homebrew include path
+	if [ -d "/opt/homebrew/include" ]
+	then
+		# This is the HomeBrew default include path on arm64
+		homebrew_path="-I/opt/homebrew/include"
+	else
+		if [ -d  "/usr/local/include" ]
+		then
+			# The default is where HomeBrew include files are installed on x86_64
+			homebrew_path="-I/usr/local/include"
+		else
+			echo "Could not find path to HomeBrew include files"
+			exit 1
+		fi
+	fi
 
     if [ -z "$SDKPATH" ]
     then
@@ -164,11 +262,11 @@ doCarbonBuild() {
         LD=$TOOLCHAIN_DIR/$LD
     fi
 
-	# There is only one way to build wx2.8.  It doesn't require a "toolkit" flag
+    # There is only one way to build wx2.8.  It doesn't require a "toolkit" flag
     # see http://wiki.wxwidgets.org/Development:_wxMac#Building_under_10.6_Snow_Leopard
     MIN_OSX_VER=`/usr/libexec/PlistBuddy -c "Print :DefaultProperties:MACOSX_DEPLOYMENT_TARGET" $SDKPATH/SDKSettings.plist`
 
-	arch_flags="-arch `uname -m`"
+    arch_flags="-arch `uname -m`"
     sdk_flags="-mmacosx-version-min=$MIN_OSX_VER -isysroot $SDKPATH"
 
     CFLAGS="     $arch_flags $sdk_flags"
@@ -204,57 +302,16 @@ then
 	if [ "$TOOLKIT" = "COCOA" ]
 	then
 		error wxWidgets $WX_VER does not support Cocoa
-    else
-        doCarbonBuild
+	else
+		doCarbonBuild
 	fi
-
 else
-	echo Building wxWidgets 2.9.X \(or later\): $WX_VER on OSX $OSX_VER
+	echo Building wxWidgets 3: $WX_VER on OSX $OSX_VER
 
 	if [ "$TOOLKIT" = "CARBON" ]
 	then
-        echo Please let PasswordSafe devs know why supporting carbon builds of wx2.9+ makes sense
-        doCarbonBuild
-    else
-
-        # This is about the only cocoa build customization we support because everything
-        # else is taken care of via "deployment target" in pwsafe-xcode5.xcodeproj
-        SDKFLAG=
-        if [ -n "$SDKPATH" ]
-        then
-            SDKFLAG="--with-macosx-sdk=$SDKPATH"
-        fi
-
-        # This is required for C++15
-        export CC=clang
-        export CPP="clang -E"
-        export CXX=clang++
-        export CXXCPP="clang++ -E"
-        export CXXFLAGS="-std=c++1y -stdlib=libc++ $homebrew_path"
-        export OBJCXXFLAGS="-std=c++1y -stdlib=libc++"
-        export LDFLAGS=-stdlib=libc++
-	if [ "$WX_VER" \> "3.0.5" ]
-        then
-            ZLIBFLAG="--with-zlib"
-            COMPATFLAG="--disable-compat30"
+		echo Please let PasswordSafe devs know why supporting carbon builds of wx3 makes sense
 	else
-            ZLIBFLAG=""
-            COMPATFLAG="--disable-compat28"
-        fi
-
-        $DRY_RUN $CONF_SCRIPT --prefix=`pwd` $DEBUG_FLAG        \
-                              $SDKFLAG                          \
-                              --with-osx_cocoa                  \
-                              --disable-shared                  \
-                              --enable-unicode                  \
-                              --enable-aui                      \
-                              --with-macosx-version-min=10.10   \
-                              $COMPATFLAG                       \
-                              --without-liblzma                 \
-                              --enable-cxx11                    \
-	                          --enable-universal-binary=`uname -m`   \
-                              $ZLIBFLAG
+		doCocoaBuild
 	fi
 fi
-
-
