Few adjustments in SlackBuild: * fixed typo in `if` condition * fixed build from path with spaces * move man and docs into /usr instead of /usr/share

diff --git a/install/slackware/passwordsafe.SlackBuild b/install/slackware/passwordsafe.SlackBuild
--- a/install/slackware/passwordsafe.SlackBuild
+++ b/install/slackware/passwordsafe.SlackBuild
@@ -2,7 +2,7 @@
 
 # Password Safe build script 
 #--
-# Last edited: 19.11.2017
+# Last edited: 07.04.2018
 #--
 
 if [ $UID = 0 ]; then
@@ -18,8 +18,8 @@ PRGNAM=passwordsafe
 
 # exit after errors
 set -e
-trap 'echo "$0 FAILED at line ${LINENO}" | tee $LOGS/error-${PRGNAM}.log' ERR
-# Catch uninitialized variables:
+trap 'echo "$0 FAILED at line ${LINENO}" | tee "${LOGS}/error-${PRGNAM}.log"' ERR
+# Catch uninitialized variables
 set -u
 # catch non-zero status in pipes
 set -o pipefail
@@ -34,8 +34,8 @@ VERSION=${VERSION:-${VER_MAJOR}.${VER_MINOR}.${VER_REV}${VER_SPECIAL}}
 ARCH=${ARCH:-x86_64} # i[345]6 or x86_64
 BUILD_ID=${BUILD_ID:-1}
 BUILDER_ID=${BUILDER_ID:-kan}
-OUTPUT=${OUTPUT:-$(pwd)/packages}
-LOGS=${LOGS:-$(pwd)/logs}
+OUTPUT=${OUTPUT:-${PWD}/packages}
+LOGS=${LOGS:-${PWD}/logs}
 MAKE_OPTIONS="-j5"
 
 ##
@@ -46,13 +46,17 @@ MAKEDIR=${GIT_ROOT}/install/slackware/build
 PKGNAME=${PRGNAM}-${VERSION/-/.}-${ARCH}-${BUILD_ID}${BUILDER_ID}
 ##
 PREFIX="/usr"
-DOCDIR=${PREFIX}/share/doc/${PRGNAM}-${VERSION}
+DOCDIR=${PREFIX}/doc/${PRGNAM}-${VERSION}
+MANDIR=${PREFIX}/man
 HELPDIR=${PREFIX}/share/${PRGNAM}/help
 XMLDIR=${PREFIX}/share/${PRGNAM}/xml
-DEFDOCDIR="/usr/share/doc/passwordsafe"
+DEFDOCDIR=${PREFIX}/share/doc/passwordsafe
+DEFMANDIR=${PREFIX}/share/man
 ##
 DATE=$(LC_ALL=C /bin/date +%d-%b-%Y)
 PKG=${PWD}/package-${PRGNAM}
+# $PKG_TMP must be subdir of $PKG, we use it later
+PKG_TMP=${PKG}/tmp
 MYDIR=${PWD}
 
 FLAGS="-DCMAKE_INSTALL_PREFIX=${PREFIX} \
@@ -103,69 +107,75 @@ PKGNAME=${PRGNAM}-${VERSION/-/.}-${ARCH}-${BUILD_ID}${BUILDER_ID}
 umask 022
 
 # Create working directories:
-mkdir -p ${LOGS}
-mkdir -p ${OUTPUT}
-mkdir -p ${PKG}
-mkdir -p ${MAKEDIR}
+mkdir -p "${LOGS}"
+mkdir -p "${OUTPUT}"
+mkdir -p "${PKG_TMP}"
+mkdir -p "${MAKEDIR}"
 # always erase old package's contents
-rm -rf ${PKG}/* ${MAKEDIR}/*
+rm -rf "${PKG}"/* "${MAKEDIR}"/*
 
 ## Package building
 echo Building ...
 cd ${MAKEDIR}
-cmake ${FLAGS} ${GIT_ROOT} 2>&1 | tee $LOGS/cmake-${PRGNAM}.log || exit 1
+cmake ${FLAGS} ${GIT_ROOT} 2>&1 | tee "${LOGS}/cmake-${PRGNAM}.log" || exit 1
 
 echo "- make"
-make ${MAKE_OPTIONS} 2>&1 | tee $LOGS/make-${PRGNAM}.log || exit 1
+make ${MAKE_OPTIONS} 2>&1 | tee "${LOGS}/make-${PRGNAM}.log" || exit 1
 
 echo "- prepare package"
-DESTDIR=${PKG} make install 2>&1 | tee $LOGS/install-${PRGNAM}.log || exit 1
+DESTDIR="${PKG_TMP}" make install 2>&1 | tee "${LOGS}/install-${PRGNAM}.log" || exit 1
 
 # collect files before packaging
 # copy docs
-mkdir -p ${PKG}/${DOCDIR}
-cp ${GIT_ROOT}/README* ${GIT_ROOT}/LICENSE ${GIT_ROOT}/install/copyright ${PKG}/${DOCDIR}
-if [-d "${PKG}${DEFDOCDIR}" ]; then
-    mv ${PKG}${DEFDOCDIR}/* ${PKG}/${DOCDIR} || true
-    rmdir ${PKG}/${DEFDOCDIR}
+mkdir -p "${PKG_TMP}${DOCDIR}"
+cp "${GIT_ROOT}"/README* "${GIT_ROOT}"/LICENSE "${GIT_ROOT}"/install/copyright "${PKG_TMP}${DOCDIR}"
+if [ -d "${PKG_TMP}${DEFDOCDIR}" ]; then
+    mv "${PKG_TMP}${DEFDOCDIR}"/* "${PKG_TMP}${DOCDIR}" || true
+    rmdir "${PKG_TMP}${DEFDOCDIR}"
+fi
+
+# move man to slackware real dir (${PREFIX}/share/man is symlink to ${PREFIX}/man)
+mkdir -p "${PKG_TMP}${MANDIR}"
+if [ -d "${PKG_TMP}${DEFMANDIR}" ]; then
+    mv "${PKG_TMP}${DEFMANDIR}"/* "${PKG_TMP}${MANDIR}" || true
+    rmdir "${PKG_TMP}${DEFMANDIR}"
 fi
 
 #copy buildscript
-mkdir -p ${PKG}/usr/src/slackbuild
-cp -a ${MYDIR}/${PRGNAM}.SlackBuild ${PKG}/usr/src/slackbuild/
+mkdir -p "${PKG_TMP}/usr/src/slackbuild"
+cp -a "${MYDIR}/${PRGNAM}.SlackBuild" "${PKG_TMP}/usr/src/slackbuild/"
 
-cd ${PKG}
+cd "${PKG_TMP}"
 # remove debugging symbols
-find . -print0 | xargs -0 file | grep "executable" | grep ELF | cut -f 1 -d : | xargs -0 strip --strip-unneeded 2> /dev/null || true
-find . -print0 | xargs -0 file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs -0 strip --strip-unneeded 2> /dev/null || true
+find . -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF | cut -f 1 -d : | xargs -0 strip --strip-unneeded 2> /dev/null || true
 
 # fix permissions
 find . -type f -print0 | xargs -0 --no-run-if-empty chmod 644
-chmod 755 ${PKG}/${PREFIX}/bin/*
+chmod 755 "${PKG_TMP}${PREFIX}/bin/"*
 
-mkdir  ${PKG}/install
+mkdir "${PKG_TMP}/install"
 
 # make slack-desc package description file
-cp ${MYDIR}/slack-desc ${PKG}/install/slack-desc
-echo "${PRGNAM}: build at ${DATE}" >> ${PKG}/install/slack-desc
+cp "${MYDIR}/slack-desc" "${PKG_TMP}/install/slack-desc"
+echo "${PRGNAM}: build at ${DATE}" >> "${PKG_TMP}/install/slack-desc"
 
 set +o xtrace
 
-ROOTCOMMANDS="set -o errexit -o xtrace -o pipefail ; cd ${PKG};
+ROOTCOMMANDS="set -o errexit -o xtrace -o pipefail ; cd \"${PKG_TMP}\";
     chown -R root:root . ;"
 ROOTCOMMANDS="${ROOTCOMMANDS}
     if [ -x /usr/bin/requiredbuilder ]; then /usr/bin/requiredbuilder -v -b -p -y .; fi ;
-    /sbin/makepkg --linkadd y --chown n ${OUTPUT}/${PKGNAME}.txz 2>&1 | tee ${LOGS}/makepkg-${PRGNAM}.log ;
-    cd ${OUTPUT};
-    md5sum ${PKGNAME}.txz > ${PKGNAME}.txz.md5;
-    rm -rf ${PKG}"
+    /sbin/makepkg --linkadd y --chown n ../${PKGNAME}.txz 2>&1 | tee \"${LOGS}/makepkg-${PRGNAM}.log\" && \
+    mv ../${PKGNAME}.txz \"${OUTPUT}\" && cd \"${OUTPUT}\" && \
+    md5sum ${PKGNAME}.txz > ${PKGNAME}.txz.md5 && \
+    rm -rf \"${PKG}\""
 
-if [ $UID = 0 ]; then
+if [ ${UID} = 0 ]; then
     eval ${ROOTCOMMANDS}
     set +o xtrace
 elif [ -x /usr/bin/fakeroot ]; then
     echo "[1mEntering fakeroot environment.[0m"
-    echo ${ROOTCOMMANDS} | /usr/bin/fakeroot
+    echo -n "${ROOTCOMMANDS}" | /usr/bin/fakeroot
 else
     echo "[1mPlease enter your root password.[0m"
     /bin/su -c "${ROOTCOMMANDS}"
