SlackBuild: get version info from version.wx

diff --git a/install/slackware/passwordsafe.SlackBuild b/install/slackware/passwordsafe.SlackBuild
--- a/install/slackware/passwordsafe.SlackBuild
+++ b/install/slackware/passwordsafe.SlackBuild
@@ -2,7 +2,7 @@
 
 # Password Safe build script 
 #--
-# Last edited: 06.01.2015
+# Last edited: 15.08.2017
 #--
 
 if [ $UID = 0 ]; then
@@ -15,22 +15,49 @@ if [ $UID = 0 ]; then
 fi
 
 PRGNAM=passwordsafe
-VERSION=${VERSION:-1.00.0beta}
+
+# exit after errors
+set -e
+trap 'echo "$0 FAILED at line ${LINENO}" | tee $LOGS/error-${PRGNAM}.log' ERR
+# Catch uninitialized variables:
+set -u
+# catch non-zero status in pipes
+set -o pipefail
+P1=${1:-1}
+
+GIT_ROOT=`git rev-parse --show-toplevel`
+sed 's/\s*=\s*/=/g' < "${GIT_ROOT}/version.wx" > "${GIT_ROOT}/version.wx.tmp"
+. "${GIT_ROOT}/version.wx.tmp"
+rm "${GIT_ROOT}/version.wx.tmp"
+
+VERSION=${VERSION:-${VER_MAJOR}.${VER_MINOR}.${VER_REV}${VER_SPECIAL}}
 ARCH=${ARCH:-x86_64} # i[345]6 or x86_64
 BUILD_ID=${BUILD_ID:-1}
 BUILDER_ID=${BUILDER_ID:-kan}
 OUTPUT=${OUTPUT:-$(pwd)/packages}
 LOGS=${LOGS:-$(pwd)/logs}
-YUBI_DISABLED=${NO_YUBI}
+YUBI_DISABLED=${NO_YUBI:-0}
+QR_DISABLED=${NO_QR:-0}
+
 if [ -n "${NO_YUBI-}" ] || [ "${NO_YUBI+x}" = x ]; then
     YUBI_DISABLED=1
 else
     YUBI_DISABLED=0
 fi
 
+if [ -n "${NO_QR-}" ] || [ "${NO_QR+x}" = x ]; then
+    QR_DISABLED=1
+else
+    QR_DISABLED=0
+fi
+
 if [ $YUBI_DISABLED -eq 1 ]; then
     VERSION="noyubi-$VERSION"
 fi
+if [ $QR_DISABLED -eq 1 ]; then
+    VERSION="noqr-$VERSION"
+fi
+
 ##
 MAKEDIR=$(pwd)/../..
 BINDIR=$(pwd)/../../src/ui/wxWidgets/GCCUnicodeRelease
@@ -57,14 +84,6 @@ MYDIR=$(pwd)
 
 MAKE_OPTIONS="-j4 release CONFIG=unicoderelease"
 
-#exit after errors
-set -e
-trap 'echo "$0 FAILED at line ${LINENO}" | tee $LOGS/error-${PRGNAM}.log' ERR
-# Catch uninitialized variables:
-set -u
-#catch non-zero status in pipes
-set -o pipefail
-P1=${1:-1}
 
 case "$ARCH" in
   i[3456]86) SLKCFLAGS="$OPTIMIZE -march=$ARCH -mtune=$ARCH"
